-- 코드를 입력하세요
SELECT
    I.NAME,
    I.DATETIME
FROM
    ANIMAL_INS AS I
    LEFT JOIN ANIMAL_OUTS AS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY -- 가장 오래 보호소에 있었던 동물 3마리
    DATETIME ASC
LIMIT 3
;